export const activityMetadataFl = `default_currency,activity_status_code,collaboration_type_code,
capital_spend_percentage,default_flow_type_code,hierarchy,
iati_identifier,default_finance_type_code,default_tied_status_code,
default_lang,reporting_org:[json],title_narrative_text,description_narrative_text,
participating_org:[json],activity_date:[json],contact_info:[json],
recipient_country:[json],sector:[json],
policy_marker:[json],default_aid_type:[json],recipient_region:[json],
planned_disbursement_type,planned_disbursement_value,planned_disbursement_value_currency,planned_disbursement_period_start_iso_date,planned_disbursement_period_end_iso_date,planned_disbursement_provider_org_narrative_text,
budget:[json],document_link_title_narrative_text,document_link_url,document_link_category_code,other_identifier:[json],humanitarian_scope_type,humanitarian_scope_vocabulary,humanitarian_scope_code,humanitarian_scope_narrative_text,
location_point_pos,location_description_narrative_text,reporting_org_narrative,reporting_org_ref,crs_add:[json],
activity_date_type,activity_date_iso_date,fss:[json],related_activity_ref,related_activity_type,tag_code,tag_narrative_text,other_identifier_ref,other_identifier_owner_org_narrative_text,
country_budget_items_vocabulary,country_budget_items_budget_item_code,country_budget_items_budget_item_percentage,country_budget_items_budget_description_narrative_text,
legacy_data_name,legacy_data_value,legacy_data_iati_equivalent,conditions_condition_type,conditions_condition_narrative_text,activity_scope_code,transaction_recipient_country_code,transaction_sector_code`;

export const activityTransactionsFl =
  "iati_identifier,transaction_date_iso_date,transaction_provider_org_narrative,transaction_receiver_org_narrative,transaction_value,transaction_value_currency,transaction_type,transaction_provider_org_provider_activity_id,transaction_receiver_org_receiver_activity_id";
