import {
  AF_COUNTRY,
  AF_COUNTRY_NAME,
  AF_DESCRIPTION_NARRATIVE,
  AF_IATI_IDENTIFIER,
  AF_PARTICIPATING_ORG_NARRATIVE,
  AF_PARTICIPATING_ORG_REF,
  AF_REPORTING_ORG_NARRATIVE,
  AF_REPORTING_ORG_REF,
  AF_TITLE_NARRATIVE,
  AF_TRANSACTION_COUNTRY,
  AF_TRANSACTION_PROVIDER_ORG_NARRATIVE,
  AF_TRANSACTION_PROVIDER_ORG_REF
} from "./apiFilterFields";

export const globalSearchFields = [
  AF_IATI_IDENTIFIER,
  AF_TITLE_NARRATIVE,
  AF_PARTICIPATING_ORG_REF,
  AF_COUNTRY,
  AF_REPORTING_ORG_NARRATIVE,
  AF_DESCRIPTION_NARRATIVE,
  AF_PARTICIPATING_ORG_NARRATIVE,
  AF_TRANSACTION_PROVIDER_ORG_REF,
  AF_TRANSACTION_PROVIDER_ORG_NARRATIVE,
  AF_TRANSACTION_COUNTRY
];

export const globalSearchSelectFields = [
  AF_IATI_IDENTIFIER,
  AF_REPORTING_ORG_REF,
  AF_TITLE_NARRATIVE,
  AF_PARTICIPATING_ORG_REF,
  AF_COUNTRY,
  AF_REPORTING_ORG_NARRATIVE,
  AF_PARTICIPATING_ORG_NARRATIVE,
  AF_TRANSACTION_PROVIDER_ORG_REF,
  AF_TRANSACTION_PROVIDER_ORG_NARRATIVE,
  AF_TRANSACTION_COUNTRY
];

export const activitySearchFields = [AF_COUNTRY, AF_TITLE_NARRATIVE];

export const donorsSearchFields = [
  AF_TRANSACTION_PROVIDER_ORG_REF,
  AF_TRANSACTION_PROVIDER_ORG_NARRATIVE
];

export const publishersSearchFields = [
  AF_REPORTING_ORG_REF,
  AF_REPORTING_ORG_NARRATIVE
];

export const sectorsSearchFields = ["", ""];

export const organisationsSearchFields = ["", ""];
